### ISSUE TITLE
Error when getting dependencies

### ISSUE THREAD

**Issue by kalaklanar** [kawarimidoll/bluestream#11]
I'm trying to run this for the first time, and I'm getting the following:
[xxxxxxx@xxxxxxxx bluestream]$ deno task dev
`Task dev deno run --allow-env=DENO_DEPLOYMENT_ID,BLUESKY_IDENTIFIER,BLUESKY_PASSWORD --allow-read=index.html,.env --allow-net=0.0.0.0,bsky.social --watch server.ts
Watcher Process started.
Download https://deno.land/std@0.192.0/async/deferred.ts 1.51KiB/1.51KiB
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/@atproto/api@0.3.12
  Lock file: /usr/local/src/bluestream/deno.lock`

**Comment by kawarimidoll** [comment]
Thank you for your reporting 🥰 
I updated dependencies to fix the issue.
