### ISSUE TITLE
Invalid date format confuses some RSS readers

### ISSUE THREAD

**Issue by kvibber** [kawarimidoll/bluestream#12]
Liferea is unable to parse the timestamps in a feed generated by bluestream, so it stores the publication time as whatever time it retrieved the feed.

I ran the feed for my Bluesky account through the [W3C feed validator](https://validator.w3.org/feed/), which turned up this issue:

> pubDate must be an RFC-822 date-time: 2023-08-29T19:59:32.672Z

It looks like the milliseconds are breaking the date validation and confusing Liferea's date parser. I've suggested that Liferea [handle this scenario](https://github.com/lwindolf/liferea/issues/1299), but I'm sure there are other feed readers out there that also parse the date strictly and won't recognize the current format.

**Comment by kawarimidoll** [comment]
Thank you for your reporting! (and thank you for reporting to Liferea)
I updated date formats to fix the issue.
